version: 2

jobs:
  build:
    working_directory: /home/launchpad

    docker:
      - image: docker:latest

    steps:
      - setup_remote_docker
      - checkout

      # install OS dependencies
      - run: apk update && apk upgrade && apk add --no-cache bash git openssh

      # run build test
      - run: .circleci/build.sh

      # deploy the build (if on a deployment branch)
      - deploy:
          name: Docker Image Deploment
          command: .circleci/deploy.sh
